# Assignment 2 - CNNs and PyTorch

### Name: Anirudh Swaminathan
### PID: A53316083
### Email ID: aswamina@ucsd.edu

#### Notebook created by Anirudh Swaminathan from ECE department majoring in Intelligent Systems, Robotics and Control for the course ECE285 Machine Learning for Image Processing for Fall 2019

## Getting Started

In [1]:
import numpy as np
import torch

## Tensors

#### Question 1

In [2]:
# Construct 5*3 tensor and print it
x = torch.Tensor(5, 3)
print(x)

# printing its type
print(type(x))

# printing its data type
print(x.dtype)

tensor([[ 0.0000e+00,  0.0000e+00,  6.0536e-43],
        [ 0.0000e+00,  2.8026e-45,  0.0000e+00],
        [-5.1365e+04,  4.5866e-41,  1.8728e-01],
        [ 3.0903e-41,         nan,         nan],
        [ 3.6434e-44,  0.0000e+00,         nan]])
<class 'torch.Tensor'>
torch.float32


$x$ was randomly initialized. $x$ is of type $\textbf{torch.Tensor}$ and it's data is of type $\text{torch.float32}$

#### Question 2

In [3]:
y = torch.rand(5, 3)
print(y)

# Finding the type of y
print(type(y))
print(y.dtype)

# Using randn() instead of rand()
y1 = torch.randn(5, 3)
print(y1)
print(type(y1))
print(y1.dtype)

tensor([[0.1166, 0.9164, 0.7950],
        [0.8535, 0.0764, 0.3186],
        [0.8876, 0.0920, 0.9408],
        [0.8671, 0.1728, 0.8849],
        [0.2735, 0.7844, 0.3328]])
<class 'torch.Tensor'>
torch.float32
tensor([[-2.0938, -0.3153,  0.4053],
        [ 1.0421, -0.1151, -1.7398],
        [-0.5421,  0.1023, -0.0370],
        [-1.5821,  0.5398, -0.0288],
        [ 0.2359, -0.0063, -0.2696]])
<class 'torch.Tensor'>
torch.float32


$y$ is a $(5, 3)$ tensor with random values distributed in a uniform distribution from $0$ to $1$<br>
$y$ is of type $\textbf{torch.Tensor}$ and it's data is of type torch.float32<br>
$y_1$ is a $(5, 3)$ tensor with random values distributed as a Gaussian with mean $0$ and variance $1$. So, $y_1$ is a tensor filled with random values from a standard normal distribution<br>
So, if we use $torch.randn()$ function instead of $torch.rand()$, we are sampling from 2 different distributions, and we may even get negative values for $torch.randn()$ but not for $torch.rand()$ function.